# Generated by Django 4.1.13 on 2024-04-24 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departemen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(default='-', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.CharField(default='-', max_length=100)),
                ('kota', models.CharField(default='-', max_length=50)),
                ('phone_number', models.CharField(default='-', max_length=15)),
                ('nik_group', models.CharField(default='-', max_length=20)),
                ('nik_lokal', models.CharField(default='-', max_length=20)),
                ('organisasi', models.CharField(default='-', max_length=100)),
                ('is_first_login', models.BooleanField(default=True)),
                ('departemen', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departemen_user', to='departemen.departemen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
