# Generated by Django 5.0.3 on 2024-03-06 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lampiran", "0001_initial"),
        ("surat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Disposisi",
            fields=[
                ("id_disposisi", models.AutoField(primary_key=True, serialize=False)),
                ("komentar", models.CharField(max_length=100)),
                ("tanggal_dispoisi", models.DateField()),
                (
                    "disposisi_kepada",
                    models.ManyToManyField(
                        related_name="disposisi_kepada", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "disposisi_oleh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disposisi_oleh",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surat",
                        to="lampiran.lampiran",
                    ),
                ),
            ],
        ),
    ]
