# Generated by Django 4.1.13 on 2024-05-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='isi_surat',
            field=models.TextField(default='-'),
        ),
    ]
