# Generated by Django 5.0.3 on 2024-03-13 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lampiran", "0001_initial"),
        ("surat", "0003_rename_tanggal_dispoisi_disposisi_tanggal_disposisi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surat",
            name="pengirim",
        ),
        migrations.AddField(
            model_name="surat",
            name="log",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="surat",
            name="id_lampiran",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lampiran_surat",
                to="lampiran.lampiran",
            ),
        ),
    ]
