# Generated by Django 5.0.3 on 2024-03-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id_divisi', models.AutoField(primary_key=True, serialize=False)),
                ('nama_divisi', models.CharField(max_length=100)),
            ],
        ),
    ]
