# Generated by Django 4.1.13 on 2024-06-13 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jabatan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(default='-', max_length=50)),
                ('alamat', models.CharField(default='-', max_length=100)),
                ('kota', models.CharField(default='-', max_length=50)),
                ('phone_number', models.CharField(default='-', max_length=15)),
                ('nik_group', models.CharField(default='-', max_length=20)),
                ('nik_lokal', models.CharField(default='-', max_length=20)),
                ('organisasi', models.CharField(default='-', max_length=100)),
                ('is_first_login', models.BooleanField(default=True)),
                ('role', models.CharField(default='User', max_length=20)),
                ('personal', models.BooleanField(default=False)),
                ('divisi', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisi_user', to='divisi.divisi')),
                ('jabatan', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jabatan_user', to='jabatan.jabatan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sekretaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('sifat', models.BooleanField(default=True)),
                ('hak_sekretaris', models.CharField(default='Biasa', max_length=50, null=True)),
                ('tgl_pembuatan', models.DateField()),
                ('atasan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sekretaris_atasan', to='profile.profile')),
                ('sekretaris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sekretaris_bawahan', to='profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Delegasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alasan', models.CharField(default='-', max_length=100, null=True)),
                ('tgl_aktif', models.DateField()),
                ('tgl_berakhir', models.DateField()),
                ('disetujui', models.BooleanField(default=False)),
                ('atasan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegasi_atasan', to='profile.profile')),
                ('delegasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegasi_bawahan', to='profile.profile')),
            ],
        ),
    ]
