# Generated by Django 4.1.13 on 2024-06-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='sekretaris',
            name='hak_sekretaris',
            field=models.CharField(default='Biasa', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sekretaris',
            name='sifat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sekretaris',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
