# Generated by Django 5.0.3 on 2024-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id_jabatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jabatan', models.CharField(max_length=100)),
            ],
        ),
    ]
