# Generated by Django 5.0.3 on 2024-03-06 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("divisi", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id_group", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.IntegerField()),
                (
                    "divisi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisi_group",
                        to="divisi.divisi",
                    ),
                ),
                (
                    "person",
                    models.ManyToManyField(
                        related_name="secretary_group", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
