# Generated by Django 5.0.3 on 2024-03-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lampiran",
            fields=[
                ("id_lampiran", models.AutoField(primary_key=True, serialize=False)),
                ("nama_lampiran", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="event_files/")),
            ],
        ),
    ]
