# Generated by Django 5.0.3 on 2024-03-05 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id_departemen', models.AutoField(primary_key=True, serialize=False)),
                ('nama_departemen', models.CharField(max_length=100)),
                ('id_divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisi', to='divisi.divisi')),
            ],
        ),
    ]
